In [1]:
import pandas as pd
import numpy as np
import scipy
df = pd.read_csv("usps-2cls.csv", header= None)

df.head()

0    1    2    3    4    5    6    7    8    9    ...  247  248  249  250  \
0    0    0   95  107    0    0    0    0    0    0  ...    0    0    0    0   
1    0   78   95    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0   42    3    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   251  252  253  254  255  256  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 257 columns]

In [2]:
class Bayes:
    def fit(self,X,y):
        classes = np.unique(y)
        cls_dict={}
        for cls in classes:
            x_cls = X[y==cls]
            mu = x_cls.mean(axis=0)
            std = np.std(x_cls, axis=0)
            d = {"mu":mu,"std":std}
            cls_dict.update({cls:d})
        self.cls_dict = cls_dict
    @staticmethod
    def _p(x, mu, std):
        a = np.exp(-np.divide((x-mu)**2,(2*std**2)))
        b = np.sqrt(2*np.pi*std**2)**-1
        return np.dot(a,b)
    def pred(self,x):
        scores=[self._p(x, **v) for v in self.cls_dict.values()]
        return np.argmax(scores)
    def predict(self, X):
        result = list(map(self.pred, X))
        return result
   
        
    
            

In [304]:
X[y==1].mean(axis=0)

(256,)

In [249]:
class Bayes:
    def fit(self,X,y):
        classes = np.unique(y)
        cls_dict={}
        for cls in classes:
            x_cls = X[y==cls]
            mu = x_cls.mean(axis=0)
            var = np.var(x_cls, axis=0)
            d = {"mu":mu,"var":var}
            cls_dict.update({cls:d})
        self.cls_dict = cls_dict
    @staticmethod
    def _p(x, mu, var):
        a = np.exp(-(x-mu)**2/(2*var))
        b = 1/np.sqrt(2*np.pi*var)
        return a*b
    def calculate_prob(self, X,mu,var):
        product = 1
        for x,m,v in zip(X,mu,var):
            product *= self._p(x, m, v)
        return product
    def predict(self,x):
        result = []
        for i in range(X.shape[0]):
            x = X[i]
            best = float("-inf")
            for key, value in self.cls_dict.items():
                mu = value["mu"]
                var = value["var"]
                score = self.calculate_prob(x,mu,var)
                if score > best:
                    best = score
                    cls = key
            result.append(cls)
        return result

In [299]:
bayes._p(X[1000],**bayes.cls_dict[0])

std = bayes.cls_dict[0]["std"]
mu = bayes.cls_dict[0]["mu"]
x = X[-5]
a = np.exp(-(x-mu)**2/(2*std**2))
b = 1/np.sqrt(2*np.pi*std**2)
sum(a*b) == np.dot(a,b)

False

In [301]:
np.dot(a,b)

4.708568364917978

In [300]:
sum(a*b)

4.708568364917982

In [253]:
a = np.exp(-(x-mu)**2/(2*var))
b = 1/np.sqrt(2*np.pi*var)

In [260]:
np.divide(-(x-mu)**2,(2*var))

array([-7.78403262e-02, -1.84099367e-01, -1.10366737e+00, -1.72391439e+00,
       -1.16049924e-01, -8.15470845e-02, -3.89337119e-02, -1.60048409e-02,
       -6.65172326e-03, -1.54453533e-03, -4.53232378e-04, -4.44961043e-04,
       -1.63805989e-03, -2.38428447e-02, -1.38253798e-01, -1.64843685e-01,
       -1.28822810e-01, -1.12688871e-01, -1.44647475e+00, -4.41217418e-01,
       -1.96576498e-01, -1.18151897e-01, -5.42824665e-02, -2.26833923e-02,
       -8.18278017e-03, -2.30344982e-03, -6.59688236e-04, -1.64603198e-03,
       -2.19020589e-02, -1.30187850e-01, -2.29543418e-02, -3.25352485e-06,
       -1.61908536e-01, -6.41417364e-02, -1.00984278e+00, -1.00940854e-02,
       -2.02222309e-01, -9.93984341e-02, -4.11590036e-02, -1.61593637e-02,
       -6.23008179e-03, -2.09250297e-03, -2.74586899e-03, -2.35515163e-02,
       -1.20041991e-01, -2.41071732e-01, -7.74033297e-01, -3.97220050e+00,
       -5.66309849e-05, -7.94454137e-01, -7.25728850e-01, -1.35658333e-02,
       -1.41001050e-01, -

In [276]:
a = np.array([4,4,4])
b = np.array([2,2,1])
np.divide(a,b)

array([2., 2., 4.])

In [156]:
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()
idx = np.where(y == 0)
x_cls = X[idx]
mu = x_cls.mean(axis=0)
var = np.cov(x_cls.T).diagonal()
x = x_cls[0,:]
1/np.sqrt(2*np.pi*var)*np.exp((x-mu)**2/(2*var))

array([0.0156581 , 0.00973879, 0.02608709, 0.04974909, 0.01059562,
       0.01151191, 0.01422168, 0.02010658, 0.03348466, 0.07267036,
       0.7786726 , 1.89106203, 0.09178186, 0.03352524, 0.01020375,
       0.0105007 , 0.00821691, 0.00448819, 0.01756735, 0.0064189 ,
       0.00519307, 0.00553411, 0.00693807, 0.01058701, 0.01822049,
       0.03038777, 0.16105569, 0.05781915, 0.01829863, 0.00693474,
       0.00385968, 0.00579751, 0.00848143, 0.00406225, 0.01065142,
       0.00393496, 0.00513024, 0.00593452, 0.00808066, 0.01251195,
       0.02020865, 0.04039158, 0.04793424, 0.01707218, 0.00690797,
       0.00489361, 0.00852415, 0.37977936, 0.0070949 , 0.00851587,
       0.00800352, 0.00403954, 0.00557644, 0.00797229, 0.01259548,
       0.01592906, 0.03212955, 0.04751516, 0.01524678, 0.00690416,
       0.00508705, 0.00408541, 0.04416536, 0.05987151, 0.01967064,
       0.00421954, 0.00615984, 0.00421769, 0.00666883, 0.01196477,
       0.01659004, 0.02330866, 0.03551787, 0.01552637, 0.00708

In [150]:
a+b

-342.683976734337

In [132]:
mu = x_cls.mean(axis=0)
Xgc = x_cls-mu
U, S, Vt = np.linalg.svd(Xgc, full_matrices=False)
S2 = (S ** 2) / (len(x_cls) - 1)
cov = np.dot(S2 * Vt.T, Vt)
cov = np.diag(cov.diagonal())
np.linalg.inv(cov)

array([[0.23062618, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.01592449, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00232436, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00218395, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00112358,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00259971]])

In [222]:
r.shape

AttributeError: 'list' object has no attribute 'shape'

In [229]:
list(map(np.argmax, np.array(r).T))

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [154]:
from sklearn.metrics import accuracy_score
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()

bayes = Bayes()
model = bayes.fit(X=X, y = y)
list(bayes.pred(X[0]))

[-inf, -inf]

In [3]:
from sklearn.metrics import accuracy_score
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()

bayes = Bayes()
model = bayes.fit(X=X, y = y)
r = bayes.predict(X)
accuracy_score(y, r)

0.5004545454545455

In [275]:
dataset = np.array([[3.393533211,2.331273381,0],
	[3.110073483,1.781539638,0],
	[1.343808831,3.368360954,0],
	[3.582294042,4.67917911,0],
	[2.280362439,2.866990263,0],
	[7.423436942,4.696522875,1],
	[5.745051997,3.533989803,1],
	[9.172168622,2.511101045,1],
	[7.792783481,3.424088941,1],
	[7.939820817,0.791637231,1]])
dataset

array([[3.39353321, 2.33127338, 0.        ],
       [3.11007348, 1.78153964, 0.        ],
       [1.34380883, 3.36836095, 0.        ],
       [3.58229404, 4.67917911, 0.        ],
       [2.28036244, 2.86699026, 0.        ],
       [7.42343694, 4.69652288, 1.        ],
       [5.745052  , 3.5339898 , 1.        ],
       [9.17216862, 2.51110105, 1.        ],
       [7.79278348, 3.42408894, 1.        ],
       [7.93982082, 0.79163723, 1.        ]])

In [268]:
from sklearn.metrics import accuracy_score
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()

bayes = Bayes()
model = bayes.fit(X=X, y = y)
r = bayes.predict(X)

In [269]:
r[-5:]

[array([5.0065346 , 5.00236415, 4.96892359, ..., 4.65302252, 4.52177758,
        4.64429884]),
 array([2.32850773, 2.2946679 , 2.38214054, ..., 2.34544915, 2.38368474,
        2.39491308])]

In [186]:
len(bayes.cls_dict[0]["var"])

256

In [169]:
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()

bayes = GaussianNB()
model = bayes.fit(X=X, y = y)
r = bayes.predict(X)
accuracy_score(y, r)

0.9595454545454546

In [75]:
from sklearn.model_selection import train_test_split
def get_score(X,y, model, p):
    test_size = 1-p
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    return score


In [287]:
n = 3

In [288]:
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1].to_numpy()
score_dict = {"p":[], "score":[]}
for p in [.1,.2,.5,.8,.9]:
    scores = []
    for i in range(n):
        bayes = Bayes() 
        score = get_score(X,y, bayes, p)
        scores.append(score)
    avg = np.round(sum(scores)/len(scores), 2)
    s = f"{p}: {avg}"
    print(s)
    score_dict["p"].append(p)
    score_dict["score"].append(avg)

/home/jfftilton/.local/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  
/home/jfftilton/.local/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in reciprocal
  from ipykernel import kernelapp as app
/home/jfftilton/.local/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  


0.1: 0.5
0.2: 0.5
0.5: 0.49
0.8: 0.49
0.9: 0.52


In [7]:
# knn
from sklearn.neighbors import KNeighborsClassifier
kneighbor_dict = {}
for k in [5,10,15,30]:
    print(f"scores for k = {k}")
    score_dict = {"p":[], "score":[]}
    for p in [.1,.2,.5,.8,.9]:
        scores = []
        for i in range(n):
            knn = KNeighborsClassifier(n_neighbors = k) 
            score = get_score(X,y, knn, p)
            scores.append(score)
        avg = np.round(sum(scores)/len(scores), 2)
        s = f"{p}: {avg}"
        print(s)
        score_dict["p"].append(p)
        score_dict["score"].append(avg)
    kneighbor_dict.update({k:score_dict})


scores for k = 5
0.1: 0.91
0.2: 0.94
0.5: 0.97
0.8: 0.97
0.9: 0.97
scores for k = 10
0.1: 0.87
0.2: 0.91
0.5: 0.95
0.8: 0.97
0.9: 0.97
scores for k = 15
0.1: 0.88
0.2: 0.92
0.5: 0.95
0.8: 0.96
0.9: 0.97
scores for k = 30
0.1: 0.84
0.2: 0.89
0.5: 0.93
0.8: 0.95
0.9: 0.95


In [286]:
# Example of calculating class probabilities
from math import sqrt
from math import pi
from math import exp

# Split the dataset by class values, returns a dictionary
def separate_by_class(dataset):
	separated = dict()
	for i in range(len(dataset)):
		vector = dataset[i]
		class_value = vector[-1]
		if (class_value not in separated):
			separated[class_value] = list()
		separated[class_value].append(vector)
	return separated

# Calculate the mean of a list of numbers
def mean(numbers):
	return sum(numbers)/float(len(numbers))

# Calculate the standard deviation of a list of numbers
def stdev(numbers):
	avg = mean(numbers)
	variance = sum([(x-avg)**2 for x in numbers]) / float(len(numbers)-1)
	return sqrt(variance)

# Calculate the mean, stdev and count for each column in a dataset
def summarize_dataset(dataset):
	summaries = [(mean(column), stdev(column), len(column)) for column in zip(*dataset)]
	del(summaries[-1])
	return summaries

# Split dataset by class then calculate statistics for each row
def summarize_by_class(dataset):
	separated = separate_by_class(dataset)
	summaries = dict()
	for class_value, rows in separated.items():
		summaries[class_value] = summarize_dataset(rows)
	return summaries

# Calculate the Gaussian probability distribution function for x
def calculate_probability(x, mean, stdev):
	exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
	return (1 / (sqrt(2 * pi) * stdev)) * exponent

# Calculate the probabilities of predicting each class for a given row
def calculate_class_probabilities(summaries, row):
	total_rows = sum([summaries[label][0][2] for label in summaries])
	probabilities = dict()
	for class_value, class_summaries in summaries.items():
		probabilities[class_value] = summaries[class_value][0][2]/float(total_rows)
		for i in range(len(class_summaries)):
			mean, stdev, _ = class_summaries[i]
			probabilities[class_value] *= calculate_probability(row[i], mean, stdev)
	return probabilities

# Test calculating class probabilities
dataset = [[3.393533211,2.331273381,0],
	[3.110073483,1.781539638,0],
	[1.343808831,3.368360954,0],
	[3.582294042,4.67917911,0],
	[2.280362439,2.866990263,0],
	[7.423436942,4.696522875,1],
	[5.745051997,3.533989803,1],
	[9.172168622,2.511101045,1],
	[7.792783481,3.424088941,1],
	[7.939820817,0.791637231,1]]
dataset = df.to_numpy()
summaries = summarize_by_class(dataset)
calculate_class_probabilities(summaries, dataset[1000,:])


{0: 0.0, 1: 0.0}

{0: [(10.860909090909091, 27.538866885652673, 1100),
  (29.862727272727273, 49.23633625526846, 1100),
  (26.592727272727274, 46.06441608569385, 1100),
  (23.688181818181818, 44.888093048269866, 1100),
  (20.36, 42.280266845340485, 1100),
  (15.176363636363636, 37.59636433178946, 1100),
  (8.134545454545455, 29.164371911035268, 1100),
  (3.6054545454545455, 20.161196779238505, 1100),
  (1.3827272727272728, 11.993624019578384, 1100),
  (0.3054545454545455, 5.498230939972299, 1100),
  (0.015454545454545455, 0.5125692857821895, 1100),
  (0.006363636363636364, 0.21105794120443525, 1100),
  (0.24909090909090909, 4.3537553567022345, 1100),
  (2.66, 12.186630303072654, 1100),
  (23.593636363636364, 44.88887660046502, 1100),
  (25.708181818181817, 44.79376791075935, 1100),
  (28.016363636363636, 55.22017890073703, 1100),
  (78.20545454545454, 99.4796268014956, 1100),
  (79.20454545454545, 96.34493581978747, 1100),
  (71.31454545454545, 96.58146418484269, 1100),
  (58.595454545454544, 93.4933248